# Configuración del Sistema AutoData Labeling

# Configuración de modelos
models:
  dinov2:
    model_size: "base"  # small, base, large, giant
    device: "auto"      # auto, cpu, cuda
    batch_size: 32
    
  clip:
    model_name: "ViT-B/32"  # ViT-B/32, ViT-B/16, ViT-L/14
    device: "auto"
    confidence_threshold: 0.3
    max_candidates: 10

# Configuración de clustering
clustering:
  algorithm: "kmeans"
  n_clusters: 8          # Número de clusters a formar
  init: "k-means++"      # k-means++, random
  n_init: 10             # Número de inicializaciones aleatorias
  max_iter: 300          # Número máximo de iteraciones
  tol: 1e-4              # Tolerancia para convergencia
  random_state: 42       # Semilla para reproducibilidad
  min_cluster_size: 3    # Tamaño mínimo de cluster válido
  
  # Configuración para optimización automática de k
  auto_k_optimization:
    enabled: false       # Activar búsqueda automática de k óptimo
    method: "silhouette" # elbow, silhouette
    k_range_min: 2       # Mínimo número de clusters a probar
    k_range_max: 15      # Máximo número de clusters a probar

# Configuración de selección de imágenes
image_selection:
  num_representatives: 3
  diversity_threshold: 0.1
  max_iterations: 100

# Configuración de clasificación
classification:
  distance_metric: "euclidean"  # euclidean, cosine, manhattan
  confidence_threshold: 0.5
  use_centroid_distance: true

# Configuración de datos
data:
  supported_extensions: [".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif", ".webp"]
  image_size_limit_mb: 50
  batch_size: 64
  cache_embeddings: true
  cache_directory: "./cache"

# Configuración de logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file_path: "./logs/autodatalabeling.log"
  max_file_size: "10MB"
  backup_count: 5
  console_output: true

# Configuración de performance
performance:
  num_workers: 4
  prefetch_factor: 2
  pin_memory: true
  use_mixed_precision: false

# Configuración de visualización
visualization:
  max_images_per_cluster: 10
  thumbnail_size: [150, 150]
  plot_style: "seaborn"
  figure_size: [12, 8]

# Configuración de evaluación
evaluation:
  metrics_to_calculate: [
    "inertia",               # Métrica específica de K-means
    "silhouette_score",      # Calidad de separación de clusters
    "calinski_harabasz_score", # Ratio de dispersión intra/inter cluster
    "cluster_balance",       # Balance en tamaños de clusters
    "labeling_confidence",   # Confianza en etiquetado CLIP
    "classification_accuracy" # Precisión de clasificación
  ]
  cross_validation_folds: 5
  test_split_ratio: 0.2

# Configuración de almacenamiento
storage:
  model_save_path: "./models"
  results_save_path: "./results"
  reports_save_path: "./reports"
  auto_save: true
  save_format: "pickle"  # pickle, json, hdf5